services:
  - type: web
    name: node-api
    env: node
    startCommand: npm start
    buildCommand: npm install
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
